services:
  backend:
    image: backend:1.0
    container_name: backend
    environment:
        REDIS: redis://redis:6379
    ports:
      - 3001:3000
    depends_on:
      - redis
    restart: on-failure:3
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
volumes:
  redis:
    driver: local
